package main

const pageTemplates = `
{{define "login"}}<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Print Cam Login</title><style>{{template "css"}}</style></head>
<body><main class="shell narrow"><h1>Print Cam</h1><section class="panel"><form id="login"><label>Email<input name="email" type="email" value="admin@example.com" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button>Continue</button></form><form id="totp" hidden><label>Authenticator code<input name="code" inputmode="numeric" autocomplete="one-time-code" required></label><button>Sign in</button></form><p id="status"></p></section></main><script>
const status = document.querySelector("#status");
document.querySelector("#login").onsubmit = async e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.target)); const res = await fetch("/api/auth/login", {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body)}); if (res.ok) { e.target.hidden = true; document.querySelector("#totp").hidden = false; status.textContent = "Enter the mandatory TOTP code."; } else status.textContent = await res.text(); };
document.querySelector("#totp").onsubmit = async e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.target)); const res = await fetch("/api/auth/totp/verify", {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body)}); if (res.ok) location.href = "/cameras"; else status.textContent = await res.text(); };
</script></body></html>{{end}}
{{define "cameras"}}<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cameras</title><style>{{template "css"}}</style></head>
<body><main class="shell"><header><h1>Cameras</h1><button id="logout">Log out</button></header><section class="toolbar"><form id="newCamera"><input name="name" placeholder="Camera name" required><button>Add camera</button></form></section><section class="grid">{{range .Cameras}}<article class="panel"><h2>{{.Name}}</h2><p class="muted">{{.ID}}</p><div class="actions"><a href="/cameras/{{.ID}}/host">Host</a><a href="/cameras/{{.ID}}/view">View</a></div></article>{{else}}<p>No cameras yet.</p>{{end}}</section></main><script>
const csrf = "{{.CSRF}}";
document.querySelector("#logout").onclick = async () => { await fetch("/api/auth/logout", {method:"POST", headers:{"X-CSRF-Token":csrf}}); location.href="/login"; };
document.querySelector("#newCamera").onsubmit = async e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.target)); const res = await fetch("/api/cameras", {method:"POST", headers:{"Content-Type":"application/json","X-CSRF-Token":csrf}, body:JSON.stringify(body)}); if (res.ok) location.reload(); };
</script></body></html>{{end}}
{{define "host"}}<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Host {{.Camera.Name}}</title><style>{{template "css"}}</style></head>
<body><main class="shell"><header><h1>{{.Camera.Name}}</h1><a href="/cameras">Cameras</a></header><section class="video"><video id="local" autoplay muted playsinline></video></section><p id="status">Starting camera...</p></main><script>
const cameraID = "{{.Camera.ID}}"; const status = document.querySelector("#status"); const peers = new Map(); let stream; let iceServers = [];
async function turn(){ const r = await fetch("/api/cameras/" + cameraID + "/turn-credentials", {method:"POST", headers:{"X-CSRF-Token":"{{.CSRF}}"}}); if(r.ok) iceServers = (await r.json()).iceServers; }
async function start(){ await turn(); stream = await navigator.mediaDevices.getUserMedia({video:true,audio:false}); document.querySelector("#local").srcObject = stream; const ws = new WebSocket((location.protocol === "https:" ? "wss" : "ws") + "://" + location.host + "/ws/host/" + cameraID); ws.onmessage = async e => { const m = JSON.parse(e.data); if(m.type==="host-ready") status.textContent="Host online. Waiting for viewers."; if(m.type==="viewer-join") await join(ws,m.viewerId); if(m.type==="answer") await peers.get(m.viewerId)?.setRemoteDescription(m.sdp); if(m.type==="ice-candidate" && m.candidate) await peers.get(m.viewerId)?.addIceCandidate(m.candidate); if(m.type==="viewer-left") { peers.get(m.viewerId)?.close(); peers.delete(m.viewerId); status.textContent=peers.size + " viewer(s) connected"; } if(m.type==="error") status.textContent=m.error; }; ws.onclose=()=>status.textContent="Host disconnected."; }
async function join(ws,id){ const pc = new RTCPeerConnection({iceServers}); peers.set(id, pc); stream.getTracks().forEach(t=>pc.addTrack(t, stream)); pc.onicecandidate = e => { if(e.candidate) ws.send(JSON.stringify({type:"ice-candidate", viewerId:id, candidate:e.candidate})); }; const offer = await pc.createOffer(); await pc.setLocalDescription(offer); ws.send(JSON.stringify({type:"offer", viewerId:id, sdp:pc.localDescription})); status.textContent=peers.size + " viewer(s) connected"; }
start().catch(err => status.textContent = err.message);
</script></body></html>{{end}}
{{define "view"}}<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>View {{.Camera.Name}}</title><style>{{template "css"}}</style></head>
<body><main class="shell"><header><h1>{{.Camera.Name}}</h1><a href="/cameras">Cameras</a></header><section class="video"><video id="remote" autoplay playsinline controls></video></section><p id="status">Connecting...</p></main><script>
const cameraID = "{{.Camera.ID}}"; const status = document.querySelector("#status"); let pc; let iceServers = [];
async function turn(){ const r = await fetch("/api/cameras/" + cameraID + "/turn-credentials", {method:"POST", headers:{"X-CSRF-Token":"{{.CSRF}}"}}); if(r.ok) iceServers = (await r.json()).iceServers; }
async function start(){ await turn(); const ws = new WebSocket((location.protocol === "https:" ? "wss" : "ws") + "://" + location.host + "/ws/view/" + cameraID); pc = new RTCPeerConnection({iceServers}); pc.ontrack = e => { document.querySelector("#remote").srcObject = e.streams[0]; status.textContent = "Live"; }; pc.onicecandidate = e => { if(e.candidate) ws.send(JSON.stringify({type:"ice-candidate", candidate:e.candidate})); }; pc.onconnectionstatechange = () => { if(pc.connectionState) status.textContent = pc.connectionState; }; ws.onmessage = async e => { const m = JSON.parse(e.data); if(m.type==="offer") { await pc.setRemoteDescription(m.sdp); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); ws.send(JSON.stringify({type:"answer", sdp:pc.localDescription})); } if(m.type==="ice-candidate" && m.candidate) await pc.addIceCandidate(m.candidate); if(m.type==="host-left") status.textContent="Host tab is offline."; if(m.type==="error") status.textContent=m.error; }; ws.onclose=()=>{ if(status.textContent !== "Live") status.textContent="Disconnected."; }; }
start().catch(err => status.textContent = err.message);
</script></body></html>{{end}}
{{define "css"}}body{margin:0;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif;background:#f4f7f5;color:#18211d}a,button{font:inherit}button,a{border:1px solid #18211d;background:#18211d;color:white;text-decoration:none;padding:.7rem 1rem;border-radius:6px;cursor:pointer}input{display:block;width:100%;box-sizing:border-box;margin-top:.35rem;padding:.75rem;border:1px solid #9aa79f;border-radius:6px;background:white}label{display:block;margin:0 0 1rem}.shell{max-width:1040px;margin:0 auto;padding:32px}.narrow{max-width:420px}.panel{background:white;border:1px solid #d8e0db;border-radius:8px;padding:20px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.actions,.toolbar,header{display:flex;gap:12px;align-items:center;justify-content:space-between}.muted{color:#5c6b63;font-size:.9rem;overflow-wrap:anywhere}.video{background:#111;border-radius:8px;overflow:hidden;aspect-ratio:16/9}video{width:100%;height:100%;object-fit:contain}#status{min-height:1.5rem;color:#334139}@media(max-width:640px){.shell{padding:18px}.actions,.toolbar,header{align-items:stretch;flex-direction:column}} {{end}}
`
